runtime: java25
instance_class: F1
service: default

# This entrypoint command tells GAE how to start your app
entrypoint: java -jar build/libs/konstantine-vashalomidze-website-0.0.1-SNAPSHOT.jar

# Vital for keeping it free: restrict scaling
automatic_scaling:
  max_instances: 1
  max_idle_instances: 0